services:
  rescueai-unified:
    build:
      context: .
      dockerfile: Dockerfile
    image: rescueai/unified:latest
    container_name: rescueai-unified
    ports:
      - "8010:8010"
    environment:
      UNIFIED_DETECTION_URL: "http://127.0.0.1:8001"
      DET_DEVICE: "cpu"
      NANODET_ONNX: "0"
      REQUIRE_NANODET_PTH: "1"
      REQUIRE_NANODET_ONNX: "0"
      NSU_LOCAL_FRAMES_DIR: "/app/public/images"
      NSU_LOCAL_FRAMES_COCO: "/app/public/annotations/val_from_labels.json"
      YOLO_WEIGHTS_URL: "https://github.com/ykvnkm/rescueai-models/releases/download/v1/yolov8n_baseline_multiscale.pt"
      NANODET_PTH_URL: "https://github.com/ykvnkm/rescueai-models/releases/download/v1/nanodet-plus-m-1.5x_416.pth"

    volumes:
      - rescueai_models:/app/models
      - rescueai_runtime:/app/runtime
      - ./public:/app/public:ro
    restart: unless-stopped

volumes:
  rescueai_models:
  rescueai_runtime:
